export const defaultGame = {
  id: 0,
  name: "",
  background_image: "",
  parent_platforms: [],
  slug: "",
  price: "$49.99",
};

export const fillerObject = {
  id: 0,
  name: "test_name",
  background_image: "test_background_image",
  image: "test_image",
  slug: "test_slug",
  parent_platforms: [],
  price: "$49.99",
  released: "test_released",
  tags: [],
  platforms: [],
  description_raw: "test_description_raw",
  developers: [],
  publishers: [],
  rating: 0,
  rating_top: 5,
  ratings: [],
  esrb_rating: [],
  updated: "test_updated",
  website: "test_website",
  screenshots: [],
  platform: {},
  genres: [],
};
