export const defaultGame = {
  id: 0,
  name: "",
  background_image: "",
  parent_platforms: [],
  slug: "",
  price: 49.99,
};

export const fillerObject = {
  id: 0,
  name: "test_name",
  background_image: "test_background_image",
  image: "test_image",
  slug: "test_slug",
  parent_platforms: [],
  price: "$49.99",
  released: "test_released",
  tags: [],
  platforms: [],
  description: "test_description",
  developers: [],
  publishers: [],
  rating: 0,
  rating_top: 5,
  ratings: 0,
  updated: "test_updated",
  website: "test_website",
  screenshots: [],
  platform: {},
};
